/**
 * AiDisclaimerBanner
 * ─────────────────────────────────────────────────────────────────────────────
 * The mandatory sticky banner displayed above any AI-generated content surface.
 * Exact wording per the governance brief — DO NOT soften without compliance
 * review.
 *
 * Variants:
 *   - generator   : shown above AI-generated test cases lists / generator output
 *   - healer      : shown above AI Healer suggestions
 *   - screenshot  : shown above auto-captured screenshots and AQM upload step
 */

import { AlertTriangle, ShieldAlert, Camera } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { useGovernance } from "@/hooks/useGovernance";
import { cn } from "@/lib/utils";

export type DisclaimerVariant = "generator" | "healer" | "screenshot";

const COPY: Record<
  DisclaimerVariant,
  { title: string; body: string; icon: typeof AlertTriangle }
> = {
  generator: {
    title: "AI-Generated Content — Requires Human Review",
    body: "This test case was generated by an AI model based on the knowledge base, business requirements, and screen analysis. AI may produce inaccurate, incomplete or non-compliant content. You are responsible for reviewing, validating, and approving the test case before it is executed against any system. By approving, you certify the test reflects the documented business and regulatory requirements.",
    icon: AlertTriangle,
  },
  healer: {
    title: "AI Self-Healing Suggestion — Manual Approval Required",
    body: "AI-generated repair logic must not be auto-applied to validated test cases. Please review the proposed fix and approve before execution. Auto-application is disabled to ensure regulatory compliance and traceability.",
    icon: ShieldAlert,
  },
  screenshot: {
    title: "AI-Captured Evidence — Reviewer Attestation Required",
    body: "Screenshots and result evidence are captured automatically by the platform. The user is responsible for reviewing screenshots before they are attached to formal validation records (AQM, ALM, Excel). You must attest that the evidence is correct, complete, and does not contain sensitive data before upload.",
    icon: Camera,
  },
};

interface AiDisclaimerBannerProps {
  variant: DisclaimerVariant;
  className?: string;
  compact?: boolean;
  /** Override visibility - default is "always show". */
  show?: boolean;
}

export function AiDisclaimerBanner({
  variant,
  className,
  compact = false,
  show = true,
}: AiDisclaimerBannerProps) {
  const { isValidated, mode } = useGovernance();
  if (!show) return null;

  const { title, body, icon: Icon } = COPY[variant];

  return (
    <Alert
      className={cn(
        "border-l-4",
        isValidated
          ? "border-l-amber-500 bg-amber-50/80 dark:bg-amber-950/30"
          : "border-l-blue-400 bg-blue-50/60 dark:bg-blue-950/30",
        className,
      )}
      data-testid={`disclaimer-${variant}`}
    >
      <Icon className={cn("h-5 w-5", isValidated ? "text-amber-600" : "text-blue-500")} />
      <div className="flex-1">
        <AlertTitle className="flex items-center gap-2 font-semibold">
          {title}
          {isValidated && (
            <Badge
              variant="outline"
              className="border-amber-500 bg-amber-100 text-amber-900 dark:bg-amber-900/40 dark:text-amber-200"
            >
              {mode.systemType}
            </Badge>
          )}
        </AlertTitle>
        {!compact && <AlertDescription className="mt-2 text-sm leading-relaxed">{body}</AlertDescription>}
      </div>
    </Alert>
  );
}
